#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7

bspc config border_width         2
bspc config window_gap          10
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Xfce4-terminal desktop='^1'
bspc rule -a jetbrains-idea desktop='^4'
bspc rule -a Chromium desktop='^2'
bspc rule -a Firefox desktop='^2'
bspc rule -a discord desktop='^3'
bspc rule -a Nemo desktop='^5'
bspc rule -a Mousepad desktop='^5'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh
wmname LG3D
